# Setting up a strategy-based portfolio

In this training module we'll see how to use LUSID to perform the following task:

**<div align="center">As a portfolio manager, I want to load transactions from two systems, each with different transaction codes, into separate investment strategies in a portfolio. I want LUSID to calculate instrument holdings grouped by strategy, and understand LUSID's view of my positions on trade date vs settlement date.</div>**

In [1]:
# Set up LUSID
import os
import pandas as pd
import json
import uuid
import matplotlib.pyplot as plt
from IPython.core.display import HTML
import logging
logging.basicConfig(level=logging.INFO)

import lusid as lu
import lusid.api as la
import lusid.models as lm

from lusid.utilities import ApiClientFactory
from lusidjam import RefreshingToken
from lusidtools.pandas_utils.lusid_pandas import lusid_response_to_data_frame
from lusidtools.jupyter_tools import StopExecution
from lusidtools.lpt.lpt import to_date

# Set pandas display options
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.options.display.float_format = "{:,.2f}".format

# Authenticate to SDK
# Run the Notebook in Jupyterhub for your LUSID domain and authenticate automatically
secrets_path = os.getenv("FBN_SECRETS_PATH")
# Run the Notebook locally using a secrets file (see https://support.lusid.com/knowledgebase/article/KA-01663)
if secrets_path is None:
    secrets_path = os.path.join(os.path.dirname(os.getcwd()), "secrets.json")

api_factory = ApiClientFactory(
    token = RefreshingToken(), 
    api_secrets_filename = secrets_path,
    app_name = "LusidJupyterNotebook"
)

# Confirm success by printing SDK version
api_status = pd.DataFrame(api_factory.build(lu.ApplicationMetadataApi).get_lusid_versions().to_dict())
display(api_status)

,api_version,build_version,excel_version,links
0,v0,0.6.8770.0,0.5.2675,"{'relation': 'RequestLogs', 'href': 'http://ja..."

In [2]:
# Specify a unique scope and code to segregate data in this module from others
module_scope = "FBNUniversity"
module_code = "Module31"

## 1. Examining the transaction source files
Note equity trades occur on 1 March 2022 but do not settle until 3 March.

In [3]:
# Read transactions from SystemA into pandas dataframe
SystemA_df = pd.read_csv("data/SystemA.csv", keep_default_na = False)
SystemA_df

,fund,instrument,isin,txn_id,txn_type,trade_date,settle_date,units,price,currency
0,Growth,GBP,,G001,FundsIn,2022-03-01,2022-03-01,100000,1.00,GBP
1,Growth,BP,GB0007980591,G002,BuyEQ,2022-03-01,2022-03-03,10000,2.05,GBP
2,Growth,Tesco,GB00BLGZ9862,G003,BuyEQ,2022-03-01,2022-03-03,8000,3.05,GBP
3,Growth,Glencore,JE00B4T3BW64,G004,BuyEQ,2022-03-01,2022-03-03,7000,4.05,GBP

In [4]:
# Read transactions from SystemB into pandas dataframe
SystemB_df = pd.read_csv("data/SystemB.csv", keep_default_na = False)
SystemB_df

,fund,instrument,isin,txn_id,txn_type,trade_date,settle_date,units,price,currency
0,Income,GBP,,I001,FundsIn,2022-03-01,2022-03-01,50000,1.00,GBP
1,Income,BP,GB0007980591,I002,Acheter,2022-03-01,2022-03-03,5000,2.10,GBP
2,Income,Unilever,GB00B10RZP78,I003,Acheter,2022-03-01,2022-03-03,3750,3.10,GBP
3,Income,Burberry,GB0031743007,I004,Acheter,2022-03-01,2022-03-03,3000,4.10,GBP

## 2. Creating a portfolio

We need to create a 'sub-holding key' (SHK) and register it with the portfolio.

### 2.1 Creating a property definition for the SHK

An SHK is a custom property and so requires a property definition in the standard way. SHKs live in the `Transaction` domain rather than `Portfolio`, since the properties are applied to transactions and not to the portfolio itself.

In [5]:
# Obtain the LUSID Property Definition API
property_definition_api = api_factory.build(la.PropertyDefinitionsApi)

# Create a property definition for the SHK in the 'Transaction' domain, with a unique scope and code
property_definition = lm.CreatePropertyDefinitionRequest(
    domain = "Transaction",
    scope = module_scope,
    code = module_code,
    display_name = "Investment strategy",
    data_type_id = lm.ResourceId(
        scope = "system",
        code = "string"
    )
)

# Upsert property definition to LUSID
try:
    upsert_property_definition_response = property_definition_api.create_property_definition(
        create_property_definition_request = property_definition
    )
    print(f"Property definition created with the following key: {upsert_property_definition_response.key}")
except lu.ApiException as e:
    if json.loads(e.body)["name"] == "PropertyAlreadyExists":
        logging.info(
            f"Property definition with the following key already exists: {property_definition.domain}/{property_definition.scope}/{property_definition.code}"
        )

# Capture SHK 3-stage property key for future use
sub_holding_key = f"{property_definition.domain}/{property_definition.scope}/{property_definition.code}"

INFO:root:Property definition with the following key already exists: Transaction/FBNUniversity/Module31

### 2.2 Creating the portfolio and registering the SHK
The SHK is registered using the `sub_holdings_keys` field.

In [6]:
# Obtain the LUSID Transaction Portfolio API
transaction_portfolios_api = api_factory.build(la.TransactionPortfoliosApi)

# Create portfolio definition
portfolio_definition=lm.CreateTransactionPortfolioRequest(
    display_name="Training module 3.1",
    code = module_code,
    base_currency = "GBP",
    # Must be before first transaction recorded
    created="2022-01-01",
    # Register the SHK property with the portfolio
    sub_holding_keys = [sub_holding_key],
)

# Upsert portfolio to LUSID, making sure it's not already there
try:
    create_portfolio_response=transaction_portfolios_api.create_portfolio(
        scope = module_scope,
        create_transaction_portfolio_request = portfolio_definition
    )
    # Confirm success
    print(f"Portfolio with display name '{create_portfolio_response.display_name}' created effective {str(create_portfolio_response.created)}")
except lu.ApiException as e:
    if json.loads(e.body)["name"] == "PortfolioWithIdAlreadyExists":
            logging.info(json.loads(e.body)["title"])

INFO:root:Could not create a portfolio with id 'Module31' because it already exists in scope 'FBNUniversity'.

## 3. Configuring transaction types to determine economic impacts

We want to create custom `BuyEQ` and `Acheter` transaction types that, when assigned to transactions representing equity purchases, have the same economic impact as the built-in `Buy` transaction type, namely to:

1. Increase your holding in each equity instrument by the number of units bought.
2. Decrease your trade date cash position in the transaction currency by the total consideration.

In [7]:
# Obtain the LUSID System Configuration API
system_config_api = api_factory.build(la.SystemConfigurationApi)

# Create a convenience function to call for each custom transaction type
def configure_new_transaction_type(transaction_code):
    transaction_type_request = lm.TransactionConfigurationDataRequest(
        # Create a new alias with the transaction code as the type (most other settings are replicated from the
        # built-in Buy transaction type)
        aliases = [
            lm.TransactionConfigurationTypeAlias(
                type = transaction_code,
                description = "The purchase of an equity",
                transaction_class = "Basic",
                # Specify a source that is different to the 'default' source of the built-in transaction types
                source = module_scope,
                transaction_roles = "LongLonger"
            )
        ],
        # Replicate the movements from the built-in Buy transaction type
        movements = [
            lm.TransactionConfigurationMovementDataRequest(
                movement_types = "StockMovement",
                side = "Side1",
                direction = 1,
                name = "Increase the holding by the number of units"
            ),
            lm.TransactionConfigurationMovementDataRequest(
                movement_types = "CashCommitment",
                side = "Side2",
                direction = -1,
                name = "Decrease cash position by total cost"
            )
        ]
    )
    
    # Upsert transaction type to LUSID    
    try:
        upsert_response = system_config_api.create_configuration_transaction_type(
            transaction_configuration_data_request = transaction_type_request
        )
        print(f"Transaction type '{transaction_code}' created.")
    except lu.ApiException as e:
        if json.loads(e.body)["name"] == "TransactionTypeDuplication":
            logging.info(
                f"Transaction type '{transaction_code}' already exists."
            )

# Create a new transaction type representing the 'BuyEQ' transaction code in SystemA
configure_new_transaction_type("BuyEQ")
# Create a new transaction type representing the 'Acheter' transaction code in SystemB
configure_new_transaction_type("Acheter")

INFO:root:Transaction type 'BuyEQ' already exists.
INFO:root:Transaction type 'Acheter' already exists.

## 4. Loading transactions into investment strategies
We assign the 3-stage property key of the SHK to the `properties` field on each transaction, with the name of the strategy as the property value.

In [8]:
# Create a convenience function to call for each vendor dataframe
def load_transactions_from_source_files(vendor_dataframe, strategy):
    
    # Create list of transactions to upsert
    transactions = []
    
    # For each row in dataframe
    for index, txn in vendor_dataframe.iterrows():
        
        # Set instrument identifiers based on whether or not instrument is cash
        if txn["txn_type"] == "FundsIn":
            identifiers = {"Instrument/default/Currency": txn["currency"]}
        else:
            identifiers = {"Instrument/default/Isin": txn["isin"]}    

        transactions.append(
            lm.TransactionRequest(
                transaction_id = txn["txn_id"],
                # Map the transaction code to a custom transaction type
                type = txn["txn_type"],
                instrument_identifiers = identifiers,
                transaction_date = txn["trade_date"],
                settlement_date = txn["settle_date"],
                units = txn["units"],
                transaction_price = lm.TransactionPrice(price = txn["price"], type="Price"),
                total_consideration = lm.CurrencyAndAmount(
                    # Calculate cost on-the-fly
                    amount = txn["units"] * txn["price"],
                    currency = txn["currency"]
                ),
                # Assign the SHK property to each transaction so it is loaded into an investment strategy
                properties = {
                    f"{sub_holding_key}": lm.PerpetualProperty(
                        key = f"{sub_holding_key}",
                        value = lm.PropertyValue(label_value = strategy)
                    )
                },
                # Identify the source of the custom transaction type (if omitted, uses the 'default' source)
                source = module_scope
            )
        )

    # Upsert transactions to LUSID
    upsert_transactions_response = transaction_portfolios_api.upsert_transactions(
        scope = module_scope, 
        code = module_code, 
        transaction_request = transactions
    )
    
    display(f"Transactions loaded at {str(upsert_transactions_response.version.as_at_date)}")
    
# Load transactions from SystemA into the portfolio's Growth strategy    
load_transactions_from_source_files(SystemA_df, "Growth")
# Load transactions from SystemB into the portfolio's Income strategy     
load_transactions_from_source_files(SystemB_df, "Income")

'Transactions loaded at 2022-03-09 14:10:46.839848+00:00'

'Transactions loaded at 2022-03-09 14:10:47.312378+00:00'

## 5. Calculating holdings grouped by strategy on the trade date

Providing we have: 

1. Registered the SHK with the portfolio
2. Applied the SHK property to each transaction

...LUSID automatically groups holdings into strategies. We can call the LUSID `GetHoldings` API with an explicit date of 1 March 2022 to understand LUSID's holding calculation on the trade date. Note `units` and `settled_units` differ for equities, and that cash lines with a `holding_type` of `C` reflect committed cash.

In [9]:
# Get holdings for portfolio effective today
get_holdings_response=transaction_portfolios_api.get_holdings(
    scope = module_scope, 
    code = module_code,
    # Specify an explicit date
    effective_at = "2022-03-01",
    # Decorate the instrument name property onto holdings to make the API response more intuitive
    property_keys=["Instrument/default/Name"],
)

# Transform API response to a pandas dataframe and show it
get_holdings_response_df=lusid_response_to_data_frame(get_holdings_response, rename_properties=True)
# Drop some noisy columns
get_holdings_response_df.drop(columns=[
    "instrument_scope", "cost_portfolio_ccy.currency", "currency", "SourcePortfolioId(default-Properties)", "SourcePortfolioScope(default-Properties)" ], inplace=True)
get_holdings_response_df

,instrument_uid,Module31(FBNUniversity-SubHoldingKeys),Name(default-Properties),holding_type,units,settled_units,cost.amount,cost.currency,cost_portfolio_ccy.amount,transaction.transaction_id,transaction.type,transaction.instrument_identifiers.Instrument/default/Isin,transaction.instrument_scope,transaction.instrument_uid,transaction.transaction_date,transaction.settlement_date,transaction.units,transaction.transaction_price.price,transaction.transaction_price.type,transaction.total_consideration.amount,transaction.total_consideration.currency,transaction.exchange_rate,transaction.transaction_currency,transaction.properties.Transaction/FBNUniversity/Module31.key,transaction.properties.Transaction/FBNUniversity/Module31.value.label_value,transaction.properties.Transaction/default/TxnInputType.key,transaction.properties.Transaction/default/TxnInputType.value.label_value,transaction.properties.Transaction/default/ResultantHolding.key,transaction.properties.Transaction/default/ResultantHolding.value.metric_value.value,transaction.source,transaction.entry_date_time
0,CCY_GBP,Growth,GBP,B,"100,000.00","100,000.00","100,000.00",GBP,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,CCY_GBP,Income,GBP,B,"50,000.00","50,000.00","50,000.00",GBP,"50,000.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,LUID_00003D5D,Growth,BP,P,"10,000.00",0.00,"20,500.00",GBP,"20,500.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,LUID_00003D5D,Income,BP,P,"5,000.00",0.00,"10,500.00",GBP,"10,500.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,LUID_IRR1P7WG,Growth,Tesco,P,"8,000.00",0.00,"24,400.00",GBP,"24,400.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
5,LUID_VUOBGVBB,Growth,Glencore,P,"7,000.00",0.00,"28,350.00",GBP,"28,350.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
6,LUID_KAZU0PDO,Income,Unilever,P,"3,750.00",0.00,"11,625.00",GBP,"11,625.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
7,LUID_EBSB2ZQK,Income,Burberry,P,"3,000.00",0.00,"12,300.00",GBP,"12,300.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
8,CCY_GBP,Growth,GBP,C,"-20,500.00",0.00,"-20,500.00",GBP,"-20,500.00",G002,Buy,GB0007980591,default,LUID_00003D5D,2022-03-01 00:00:00+00:00,2022-03-03 00:00:00+00:00,"10,000.00",2.05,Price,"20,500.00",GBP,1.00,GBP,Transaction/FBNUniversity/Module31,Growth,Transaction/default/TxnInputType,BuyEQ,Transaction/default/ResultantHolding,"10,000.00",FBNUniversity,2022-03-09 14:10:46.839848+00:00
9,CCY_GBP,Growth,GBP,C,"-24,400.00",0.00,"-24,400.00",GBP,"-24,400.00",G003,Buy,GB00BLGZ9862,default,LUID_IRR1P7WG,2022-03-01 00:00:00+00:00,2022-03-03 00:00:00+00:00,"8,000.00",3.05,Price,"24,400.00",GBP,1.00,GBP,Transaction/FBNUniversity/Module31,Growth,Transaction/default/TxnInputType,BuyEQ,Transaction/default/ResultantHolding,"8,000.00",FBNUniversity,2022-03-09 14:10:46.839848+00:00
10,CCY_GBP,Growth,GBP,C,"-28,350.00",0.00,"-28,350.00",GBP,"-28,350.00",G004,Buy,JE00B4T3BW64,default,LUID_VUOBGVBB,2022-03-01 00:00:00+00:00,2022-03-03 00:00:00+00:00,"7,000.00",4.05,Price,"28,350.00",GBP,1.00,GBP,Transaction/FBNUniversity/Module31,Growth,Transaction/default/TxnInputType,BuyEQ,Transaction/default/ResultantHolding,"7,000.00",FBNUniversity,2022-03-09 14:10:46.839848+00:00
11,CCY_GBP,Income,GBP,C,"-10,500.00",0.00,"-10,500.00",GBP,"-10,500.00",I002,Buy,GB0007980591,default,LUID_00003D5D,2022-03-01 00:00:00+00:00,2022-03-03 00:00:00+00:00,"5,000.00",2.10,Price,"10,500.00",GBP,1.00,GBP,Transaction/FBNUniversity/Module31,Income,Transaction/default/TxnInputType,Acheter,Transaction/default/ResultantHolding,"5,000.00",FBNUniversity,2022-03-09 14:10:47.312378+00:00
12,CCY_GBP,Income,GBP,C,"-11,625.00",0.00,"-11,625.00",GBP,"-11,625.00",I003,Buy,GB00B10RZP78,default,LUID_KAZU0PDO,2022-03-01 00:00:00+00:00,2022-03-03 00:00:00+00:00,"3,750.00",3.10,Price,"11,625.00",GBP,1.00,GBP,Transaction/FBNUniversity/Module31,Income,Transaction/default/TxnInputType,Acheter,Transaction/default/ResultantHolding,"3,750.00",FBNUniversity,2022-03-09 14:10:47.312378+00:00
13,CCY_GBP,Income,GBP,C,"-12,300.00",0.00,"-12,300.00",GBP,"-12,300.00",I004,Buy,GB0031743007,default,LUID_EBSB2ZQK,2022-03-01 00:00:00+00:00,2022-03-03 00:00:00+00:00,"3,000.00",4.10,Price,"12,300.00",GBP,1.00,GBP,Transaction/FBNUniversity/Module31,Income,Transaction/default/TxnInputType,Acheter,Transaction/default/ResultantHolding,"3,000.00",FBNUniversity,2022-03-09 14:10:47.312378+00:00

## 6. Calculating holdings again post settlement date

If we call `GetHoldings` API without an explicit date, LUSID uses today's date. Since this is after the settlement date, we can see that `units` and `settled_units` are now the same for equities, and that cash has been disbursed.

In [10]:
# Get holdings for portfolio effective a particular day
get_holdings_response=transaction_portfolios_api.get_holdings(
    scope = module_scope, 
    code = module_code,
    #Decorate the instrument name property onto holdings to make the API response more intuitive
    property_keys=["Instrument/default/Name"],
)

# Transform API response to a pandas dataframe and show it
get_holdings_response_df=lusid_response_to_data_frame(get_holdings_response, rename_properties=True)
# Drop some noisy columns
get_holdings_response_df.drop(columns=[
    "instrument_scope", "cost_portfolio_ccy.currency", "currency", "SourcePortfolioId(default-Properties)", "SourcePortfolioScope(default-Properties)"], inplace=True)
get_holdings_response_df

,instrument_uid,Module31(FBNUniversity-SubHoldingKeys),Name(default-Properties),holding_type,units,settled_units,cost.amount,cost.currency,cost_portfolio_ccy.amount
0,CCY_GBP,Growth,GBP,B,"26,750.00","26,750.00","26,750.00",GBP,"26,750.00"
1,CCY_GBP,Income,GBP,B,"15,575.00","15,575.00","15,575.00",GBP,"15,575.00"
2,LUID_00003D5D,Growth,BP,P,"10,000.00","10,000.00","20,500.00",GBP,"20,500.00"
3,LUID_00003D5D,Income,BP,P,"5,000.00","5,000.00","10,500.00",GBP,"10,500.00"
4,LUID_IRR1P7WG,Growth,Tesco,P,"8,000.00","8,000.00","24,400.00",GBP,"24,400.00"
5,LUID_VUOBGVBB,Growth,Glencore,P,"7,000.00","7,000.00","28,350.00",GBP,"28,350.00"
6,LUID_KAZU0PDO,Income,Unilever,P,"3,750.00","3,750.00","11,625.00",GBP,"11,625.00"
7,LUID_EBSB2ZQK,Income,Burberry,P,"3,000.00","3,000.00","12,300.00",GBP,"12,300.00"