# Reconciling end-of-day positions with an external system

In this training module we'll see how to use LUSID to perform the following task:

**<div align="center">As a portfolio manager, I want to load start-of-day positions, intra-day transactions, and end-of-day positions from an external system, and then reconcile LUSID's holdings calculation with that of the external system.</div>**

In [1]:
# Set up LUSID
import os
import pandas as pd
import json
import uuid
import matplotlib.pyplot as plt
from IPython.core.display import HTML
import logging
logging.basicConfig(level=logging.INFO)
from datetime import datetime, timedelta

import lusid as lu
import lusid.api as la
import lusid.models as lm

from lusid.utilities import ApiClientFactory
from lusidjam import RefreshingToken
from lusidtools.pandas_utils.lusid_pandas import lusid_response_to_data_frame
from lusidtools.jupyter_tools import StopExecution
from lusidtools.lpt.lpt import to_date

# Set pandas display options
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.options.display.float_format = "{:,.2f}".format

# Authenticate to SDK
# Run the Notebook in Jupyterhub for your LUSID domain and authenticate automatically
secrets_path = os.getenv("FBN_SECRETS_PATH")
# Run the Notebook locally using a secrets file (see https://support.lusid.com/knowledgebase/article/KA-01663)
if secrets_path is None:
    secrets_path = os.path.join(os.path.dirname(os.getcwd()), "secrets.json")

api_factory = ApiClientFactory(
    token = RefreshingToken(), 
    api_secrets_filename = secrets_path,
    app_name = "LusidJupyterNotebook"
)

# Confirm success by printing SDK version
api_status = pd.DataFrame(api_factory.build(lu.ApplicationMetadataApi).get_lusid_versions().to_dict())
display(api_status)

,api_version,build_version,excel_version,links
0,v0,0.6.8800.0,0.5.2682,"{'relation': 'RequestLogs', 'href': 'http://ja..."

In [2]:
# Create a scope and code to segregate data in this module from other modules
module_scope = "FBNUniversity"
module_code = "Module32"

## 1. Examining the source files

In [3]:
# Read start-of-day positions into Pandas dataframe
SOD_positions_df = pd.read_csv("data/positions-sod.csv", keep_default_na = False)
SOD_positions_df

      Asset   Class          Isin  Quantity  Price
0       GBP    Cash                   50000   1.00
1        BP  Equity  GB0007980591      5000   2.00
2  Unilever  Equity  GB00B10RZP78      4000   3.00

In [4]:
# Read intra-day transactions into dataframe
transactions_df = pd.read_csv("data/transactions.csv", keep_default_na = False)
transactions_df

,instrument,isin,txn_id,txn_type,trade_date,units,price,currency
0,BP,GB0007980591,MD32001,Buy,2022-03-07T12:00:00Z,10000,2.00,GBP
1,Unilever,GB00B10RZP78,MD32002,Sell,2022-03-07T12:10:00Z,3000,3.00,GBP

In [5]:
# Read end-of-day positions into dataframe
EOD_positions_df = pd.read_csv("data/positions-eod.csv", keep_default_na = False)
EOD_positions_df

      Asset   Class          Isin  Quantity  Price
0       GBP    Cash                   38000   1.00
1        BP  Equity  GB0007980591     14900   2.00
2  Unilever  Equity  GB00B10RZP78      1010   3.00

## 2. Creating a suitable portfolio

In [6]:
# Obtain the LUSID Transaction Portfolio API
transaction_portfolios_api = api_factory.build(la.TransactionPortfoliosApi)

# Create portfolio definition
portfolio_definition=lm.CreateTransactionPortfolioRequest(
    display_name="Training module 3.2",
    code = module_code,
    base_currency = "GBP",
    # Must be before first transaction recorded
    created="2022-01-01",
)

# Upsert portfolio to LUSID, making sure it's not already there
try:
    create_portfolio_response=transaction_portfolios_api.create_portfolio(
        scope = module_scope,
        create_transaction_portfolio_request = portfolio_definition
    )
    # Confirm success
    print(f"Portfolio with display name '{create_portfolio_response.display_name}' created effective {str(create_portfolio_response.created)}")
except lu.ApiException as e:
    if json.loads(e.body)["name"] == "PortfolioWithIdAlreadyExists":
            logging.info(json.loads(e.body)["title"])

INFO:root:Could not create a portfolio with id 'Module32' because it already exists in scope 'FBNUniversity'.

## 3 Setting up cut labels
A LUSID 'cut label' replaces the time portion of a datetime with a meaningful name, to make working across time zones more intuitive.

In [12]:
# Obtain the LUSID CutLabelDefinitions API
cut_label_definition_api = api_factory.build(la.CutLabelDefinitionsApi)

# Create a convenience function to either create a cut label or update an existing one
def create_or_update_cut_label(code, description, name, time, zone):
    # Create new cut label if one with the same code doesn't exist...
    try:
        request = lm.CutLabelDefinition(
            code = code, 
            description = description, 
            display_name = name,
            cut_local_time = lm.CutLocalTime(
                hours = time[0:2],
                minutes = time[3:5]
            ),
            time_zone = zone,
        )
        cut_label_definition_api.create_cut_label_definition(
            create_cut_label_definition_request = request
        )
        print(f"Cut label with code {code} created.")
    # ...else update existing cut label
    except lu.ApiException as e:
        request = lm.UpdateCutLabelDefinitionRequest(
            display_name = name,
            description = description,
            cut_local_time = lm.CutLocalTime(
                hours = time[0:2],
                minutes = time[3:5]
            ),
            time_zone = zone,
        )
        cut_label_definition_api.update_cut_label_definition(
            code = code,
            update_cut_label_definition_request = request
        )
        print(f"Cut label with code {code} updated.")

create_or_update_cut_label("LDN_Open", "LondonOpen", "London Market Open Time", "08:00", "Europe/London")
create_or_update_cut_label("LDN_Close", "LondonClose", "London Market Close Time", "16:30", "Europe/London")

Cut label with code LDN_Open updated.
Cut label with code LDN_Close updated.

## 4. Loading start-of-day positions
We can call the LUSID `SetHoldings` API with the built-in `LDN_Open` cut label to set the datetime of each adjustment transaction to precisely 8:00am UTC on 7 March 2022.

In [8]:
# Create convenience function to call
def load_positions(dataframe, cutlabel):
    
    holdings = []
    
    # Iterate over rows in the dataframe, creating one adjustment transaction per row
    for index, row in dataframe.iterrows():
        
        # Specify different identifiers for equities and cash
        if row["Class"] == "Cash":
            identifiers = {"Instrument/default/Currency": row["Asset"]}
        else:
            identifiers = {"Instrument/default/Isin": row["Isin"]}

        holdings.append(
            lm.AdjustHoldingRequest(
                instrument_identifiers = identifiers,
                tax_lots = [
                    lm.TargetTaxLotRequest(
                        units = row["Quantity"],
                        cost = lm.CurrencyAndAmount(
                            # Calculate cost on the fly
                            amount = row["Quantity"] * row["Price"],
                            # Have to set holding currency to same as transaction currency, even if cost basis is 0
                            currency="GBP"
                        ),
                        portfolio_cost = row["Quantity"] * row["Price"],
                        price = row["Price"]
                    )
                ]
            )
        )

    # Set holdings in LUSID (restate any existing holdings)
    set_holdings_response=transaction_portfolios_api.set_holdings(
        scope=module_scope,
        code=module_code,
        # Make holdings effective from the time of the cut label on 7 March 2022. Note use of 'N' separator
        # between date and cut label time
        effective_at = f"2022-03-07N{cutlabel}",
        adjust_holding_request=holdings
    )
    
    # Confirm by calling GetHoldings
    get_holdings_response=transaction_portfolios_api.get_holdings(
        scope = module_scope, 
        code = module_code,
        effective_at = f"2022-03-07N{cutlabel}",
        # Decorate on instrument name property to make more results more intuitive
        property_keys = ["Instrument/default/Name"]
    )
    # Transform GetHoldings response to a Pandas dataframe and show it
    get_holdings_response_df=lusid_response_to_data_frame(get_holdings_response, rename_properties=True)
    # Drop some noisy columns
    get_holdings_response_df.drop(columns=[
        "instrument_scope", "sub_holding_keys", "cost_portfolio_ccy.currency", "currency", "SourcePortfolioId(default-Properties)", "SourcePortfolioScope(default-Properties)"], inplace=True)
    display(get_holdings_response_df)

# Load start-of-day positions into LUSID effective 8:00am UTC
load_positions(SOD_positions_df, "LDN_Open")

,instrument_uid,Name(default-Properties),holding_type,units,settled_units,cost.amount,cost.currency,cost_portfolio_ccy.amount
0,LUID_00003D5D,BP,P,"5,000.00","5,000.00","10,000.00",GBP,"10,000.00"
1,LUID_KAZU0PDO,Unilever,P,"4,000.00","4,000.00","12,000.00",GBP,"12,000.00"
2,CCY_GBP,GBP,B,"50,000.00","50,000.00","50,000.00",GBP,"50,000.00"

## 5. Loading intra-day transactions

In [9]:
# Create convenience function to call
def load_transactions_from_source_file(vendor_dataframe):
    
    # Iterate over rows in the dataframe, creating one transaction per row
    transactions = [
        lm.TransactionRequest(
            transaction_id = row["txn_id"],
            type = row["txn_type"],
            instrument_identifiers = {"Instrument/default/Isin": row["isin"]},
            # Use LPT to_date function to convert to UTC datetime
            transaction_date = to_date(row["trade_date"]),
            # Settlement date is 2 days later
            settlement_date = to_date(row["trade_date"]) + timedelta(days = 2),
            units = row["units"],
            transaction_price = lm.TransactionPrice(price = row["price"], type="Price"),
            total_consideration = lm.CurrencyAndAmount(
                # Calculate cost on the fly
                amount = row["units"] * row["price"],
                currency = row["currency"]
            ),
            transaction_currency = row["currency"]
        )
        for index, row in vendor_dataframe.iterrows()
    ]

    # Upsert transactions to LUSID
    upsert_transactions_response = transaction_portfolios_api.upsert_transactions(
        scope = module_scope, 
        code = module_code, 
        transaction_request = transactions
    )
        
    # Confirm by calling GetHoldings
    get_holdings_response=transaction_portfolios_api.get_holdings(
        scope = module_scope, 
        code = module_code,
        # Note use of 'T' separator between date and explicit time
        effective_at = "2022-03-07T16:29:00Z",
        property_keys = ["Instrument/default/Name"]
    )
    # Transform API response to a pandas dataframe and show it
    get_holdings_response_df=lusid_response_to_data_frame(get_holdings_response, rename_properties=True)
    # Drop some noisy columns
    get_holdings_response_df.drop(columns=[
        "instrument_scope", "sub_holding_keys", "cost_portfolio_ccy.currency", "currency", "SourcePortfolioId(default-Properties)", "SourcePortfolioScope(default-Properties)"], inplace=True)
    display(get_holdings_response_df)
    
# Load intra-day transactions   
load_transactions_from_source_file(transactions_df)

,instrument_uid,Name(default-Properties),holding_type,units,settled_units,cost.amount,cost.currency,cost_portfolio_ccy.amount,transaction.transaction_id,transaction.type,transaction.instrument_identifiers.Instrument/default/Isin,transaction.instrument_scope,transaction.instrument_uid,transaction.transaction_date,transaction.settlement_date,transaction.units,transaction.transaction_price.price,transaction.transaction_price.type,transaction.total_consideration.amount,transaction.total_consideration.currency,transaction.exchange_rate,transaction.transaction_currency,transaction.properties.Transaction/default/ResultantHolding.key,transaction.properties.Transaction/default/ResultantHolding.value.metric_value.value,transaction.entry_date_time
0,LUID_00003D5D,BP,P,"15,000.00","5,000.00","30,000.00",GBP,"30,000.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,LUID_KAZU0PDO,Unilever,P,"1,000.00","4,000.00","3,000.00",GBP,"3,000.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,CCY_GBP,GBP,B,"50,000.00","50,000.00","50,000.00",GBP,"50,000.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,CCY_GBP,GBP,C,"-20,000.00",0.00,"-20,000.00",GBP,"-20,000.00",MD32001,Buy,GB0007980591,default,LUID_00003D5D,2022-03-07 12:00:00+00:00,2022-03-09 12:00:00+00:00,"10,000.00",2.00,Price,"20,000.00",GBP,1.00,GBP,Transaction/default/ResultantHolding,"15,000.00",2022-03-11 16:45:37.120521+00:00
4,CCY_GBP,GBP,C,"9,000.00",0.00,"9,000.00",GBP,"9,000.00",MD32002,Sell,GB00B10RZP78,default,LUID_KAZU0PDO,2022-03-07 12:10:00+00:00,2022-03-09 12:10:00+00:00,"3,000.00",3.00,Price,"9,000.00",GBP,1.00,GBP,Transaction/default/ResultantHolding,"1,000.00",2022-03-11 16:45:37.120521+00:00

## 6. Load external system's view of EOD positions
We can call the LUSID `SetHoldings` API again, this time with the built-in `LDN_Close` cut label to set the datetime of each adjustment transaction to precisely 4:30pm UTC on 7 March 2022.

In [10]:
# Load end-of-day positions into LUSID effective 4:30pm UTC
load_positions(EOD_positions_df, "LDN_Close")

,instrument_uid,Name(default-Properties),holding_type,units,settled_units,cost.amount,cost.currency,cost_portfolio_ccy.amount,transaction.transaction_id,transaction.type,transaction.instrument_identifiers.Instrument/default/Isin,transaction.instrument_scope,transaction.instrument_uid,transaction.transaction_date,transaction.settlement_date,transaction.units,transaction.transaction_price.price,transaction.transaction_price.type,transaction.total_consideration.amount,transaction.total_consideration.currency,transaction.exchange_rate,transaction.transaction_currency,transaction.properties.Transaction/default/ResultantHolding.key,transaction.properties.Transaction/default/ResultantHolding.value.metric_value.value,transaction.entry_date_time
0,LUID_00003D5D,BP,P,"14,900.00","4,900.00","29,800.00",GBP,"29,800.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,LUID_KAZU0PDO,Unilever,P,"1,010.00","4,010.00","3,030.00",GBP,"3,030.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,CCY_GBP,GBP,B,"38,000.00","38,000.00","38,000.00",GBP,"38,000.00",NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,CCY_GBP,GBP,C,"-20,000.00",0.00,"-20,000.00",GBP,"-20,000.00",MD32001,Buy,GB0007980591,default,LUID_00003D5D,2022-03-07 12:00:00+00:00,2022-03-09 12:00:00+00:00,"10,000.00",2.00,Price,"20,000.00",GBP,1.00,GBP,Transaction/default/ResultantHolding,"15,000.00",2022-03-11 16:45:37.120521+00:00
4,CCY_GBP,GBP,C,"9,000.00",0.00,"9,000.00",GBP,"9,000.00",MD32002,Sell,GB00B10RZP78,default,LUID_KAZU0PDO,2022-03-07 12:10:00+00:00,2022-03-09 12:10:00+00:00,"3,000.00",3.00,Price,"9,000.00",GBP,1.00,GBP,Transaction/default/ResultantHolding,"1,000.00",2022-03-11 16:45:37.120521+00:00

## 7. Reconcile LUSID's view vs. external system's view

We can call the LUSID `ReconcileHoldings` API and:

* On the left-hand side pass in the portfolio at 4:29pm on 7 March 2022, which is LUSID's calculation of holdings.
* On the right-hand side pass in the same portfolio at 4:30pm (`LDN_Close`), which is the external system's view of positions.

In [11]:
# Obtain the Reconciliations API
reconciliations_api=api_factory.build(la.ReconciliationsApi)

# Create reconcilation request
reconcile_holdings_request = lm.PortfoliosReconciliationRequest(
    # Pass in the portfolio at 4:29pm on the left
    left = lm.PortfolioReconciliationRequest(
        portfolio_id = lm.ResourceId(
            scope = module_scope,
            code = module_code
        ),
        # Note 'T' separator between date and explicit time
        effective_at = "2022-03-07T16:29:00Z"
    ),
    # Pass in the portfolio at LDN_Close, which is 4:30pm, on the right
    right = lm.PortfolioReconciliationRequest(
        portfolio_id = lm.ResourceId(
            scope = module_scope,
            code = module_code
        ),
        # Note 'N' separator between date and cut label time
        effective_at = "2022-03-07NLDN_Close"
    ),
    # Decorate on instrument name property to make results more intuitive
    instrument_property_keys = ["Instrument/default/Name"]
)

# Reconcile holdings
get_reconciliation_response = reconciliations_api.reconcile_holdings(
    portfolios_reconciliation_request = reconcile_holdings_request
)

# Transform API response to a Pandas dataframe and show it
get_reconciliation_response_df=lusid_response_to_data_frame(get_reconciliation_response, rename_properties=True)
# Drop some noisy columns
get_reconciliation_response_df.drop(columns=[
    "sub_holding_keys", "instrument_properties.0.effective_from", "instrument_properties.0.key"], inplace=True)
get_reconciliation_response_df

,instrument_uid,left_units,right_units,difference_units,left_cost.amount,left_cost.currency,right_cost.amount,right_cost.currency,difference_cost.amount,difference_cost.currency,instrument_properties.0.value.label_value
0,LUID_00003D5D,"15,000.00","14,900.00",-100.00,"30,000.00",GBP,"29,800.00",GBP,-200.00,GBP,BP
1,LUID_KAZU0PDO,"1,000.00","1,010.00",10.00,"3,000.00",GBP,"3,030.00",GBP,30.00,GBP,Unilever
2,CCY_GBP,"39,000.00","27,000.00","-12,000.00","39,000.00",GBP,"27,000.00",GBP,"-12,000.00",GBP,GBP