# Paging and limiting LUSID's API calls

This notebooks shows how you can use the <b>limit</b> and <b>page</b> parameters of a LUSID call to slice up large requests into numerous smaller requests. For the purposes of this demonstration, we will use the [<b>list instruments</b>](https://www.lusid.com/docs/api/#operation/ListInstruments) API.

## Setup LUSID

In [1]:
# Import general purpose Python packages
import os

# Import lusid specific packages
# These are the core lusid packages for interacting with the API via Python
import lusid
import lusid.models as models
from lusid.utilities import ApiClientFactory
from lusidjam.refreshing_token import RefreshingToken
from lusidtools.pandas_utils.lusid_pandas import lusid_response_to_data_frame

# Import data wrangling packages
import pandas as pd
import json

# Authenticate our user and create our API client
secrets_path = os.getenv("FBN_SECRETS_PATH")

# Initiate an API Factory which is the client side object for interacting with LUSID APIs
api_factory = lusid.utilities.ApiClientFactory(
    token=RefreshingToken(),
    api_secrets_filename = secrets_path,
    app_name="LusidJupyterNotebook")

In [2]:
# Load a mapping file for formatting DataFrame columns

with open(r"config/list_instruments_mapping.json") as mappings_file:
    json_mappings = json.load(mappings_file)

## Create an instruments API object and call the "list instruments" method

In [3]:
instruments_api = api_factory.build(lusid.api.InstrumentsApi)

In [4]:
list_instruments = instruments_api.list_instruments()
lusid_response_to_data_frame(list_instruments,
                             column_name_mapping=json_mappings).drop(columns={"href"}).head(10)

,Luid,EffectiveFrom,AsAt,InstrumentName,Currency,LusidInstrumentId,properties,state,Isin,Figi,Ticker,ClientInternalId,Sedol,Format,Content,LTScope,LTCode
0,CCY_AED,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,AED,AED,CCY_AED,[],Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CCY_AFN,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,AFN,AFN,CCY_AFN,[],Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CCY_ALL,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,ALL,ALL,CCY_ALL,[],Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CCY_AMD,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,AMD,AMD,CCY_AMD,[],Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CCY_ANG,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,ANG,ANG,CCY_ANG,[],Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CCY_AOA,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,AOA,AOA,CCY_AOA,[],Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,CCY_ARS,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,ARS,ARS,CCY_ARS,[],Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,CCY_ATS,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,ATS,ATS,CCY_ATS,[],Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,CCY_AUD,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,AUD,AUD,CCY_AUD,[],Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,CCY_AWG,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,AWG,AWG,CCY_AWG,[],Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Get a list of instruments, limited to 100 returned items

In [5]:
first_list_instruments_response = instruments_api.list_instruments(limit=100)
lusid_response_to_data_frame(first_list_instruments_response,
                             column_name_mapping=json_mappings).drop(columns={"href"})

,Luid,EffectiveFrom,AsAt,InstrumentName,Currency,LusidInstrumentId,properties,state
0,CCY_AED,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,AED,AED,CCY_AED,[],Active
1,CCY_AFN,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,AFN,AFN,CCY_AFN,[],Active
2,CCY_ALL,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,ALL,ALL,CCY_ALL,[],Active
3,CCY_AMD,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,AMD,AMD,CCY_AMD,[],Active
4,CCY_ANG,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,ANG,ANG,CCY_ANG,[],Active
...,...,...,...,...,...,...,...,...
95,CCY_LAK,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,LAK,LAK,CCY_LAK,[],Active
96,CCY_LBP,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,LBP,LBP,CCY_LBP,[],Active
97,CCY_LKR,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,LKR,LKR,CCY_LKR,[],Active
98,CCY_LRD,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,LRD,LRD,CCY_LRD,[],Active
99,CCY_LSL,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,LSL,LSL,CCY_LSL,[],Active

In [6]:
# get the token for the next page, this will be empty if it is the last page
next_page_token = first_list_instruments_response.next_page

# get the token for the previous page
previous_page_token = first_list_instruments_response.previous_page

In [7]:
print(f"The token for the next page is {next_page_token}")
print(f"The token for the previous page is {previous_page_token}")

The token for the next page is iDZU6gAqF5Dds9XXCDggfWaz1dcIQ0NZX0xTTA==
The token for the previous page is Vyr84QEqF5Dds9XXCDggfWaz1dcIQ0NZX0FFRA==

## Get the next 100 instruments

In [8]:
# The next page token is passed to the page parameter

second_list_instruments_response = instruments_api.list_instruments(
    page=next_page_token, limit=100)

lusid_response_to_data_frame(second_list_instruments_response,
                             column_name_mapping=json_mappings).drop(columns={"href"})

,Luid,EffectiveFrom,AsAt,InstrumentName,LusidInstrumentId,Currency,properties,state
0,CCY_LTL,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,LTL,CCY_LTL,LTL,[],Active
1,CCY_LVL,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,LVL,CCY_LVL,LVL,[],Active
2,CCY_LYD,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,LYD,CCY_LYD,LYD,[],Active
3,CCY_MAD,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,MAD,CCY_MAD,MAD,[],Active
4,CCY_MDL,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,MDL,CCY_MDL,MDL,[],Active
...,...,...,...,...,...,...,...,...
95,CCY_YER,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,YER,CCY_YER,YER,[],Active
96,CCY_ZAR,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,ZAR,CCY_ZAR,ZAR,[],Active
97,CCY_ZMK,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,ZMK,CCY_ZMK,ZMK,[],Active
98,CCY_ZMW,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,ZMW,CCY_ZMW,ZMW,[],Active
99,CCY_ZWD,0001-01-01 00:00:00+00:00,2020-03-31 20:37:59.155308+00:00,ZWD,CCY_ZWD,ZWD,[],Active